UserRepository and UserService tests and implementations
kealyz/evoKnowledgeShare pull request #20
Opened 2022-11-04 15:05 UTC by SzAndras1

2022-11-04 15:07 UTC, kealyz submitted a review, later dismissed

2022-11-05 23:08 UTC, vadaszidavid requested changes

2022-11-05 23:08 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.Backend/Models/User.cs
> +using System.Drawing;
Ne legyenek fölösleges using-ok

2022-11-05 23:08 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.Backend/Repositories/UserRepository.cs
> +using System.Runtime.CompilerServices;
Ne legyenek fölösleges using-ok

2022-11-05 23:08 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.Backend/Repositories/UserRepository.cs
> +        public override Task AddRangeAsync(IEnumerable<User> entities) => throw new NotImplementedException();
Ne dobjunk NotImplementedException-t, ha nem akarunk ilyet támogatni, akkor legen NotSupportedException. Ha pedig véletlenül kimaradt, akkor legyen megcsinálva mindenhol

2022-11-05 23:08 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.UnitTests/Services/UserServiceTests.cs
> +using Microsoft.OpenApi.Validations;
Ne legyenek fölösleges using-ok

2022-11-08 18:05 UTC, kealyz approved these changes

2022-11-08 18:07 UTC, vadaszidavid approved these changes

2022-11-08 18:07 UTC, merged

2022-11-08 18:07 UTC, vadaszidavid approved these changes