Refactor UserRepository, UserService and their Tests
kealyz/evoKnowledgeShare pull request #22
Opened 2022-11-18 00:39 UTC by SzAndras1

2022-11-18 14:52 UTC, vadaszidavid requested changes
.

2022-11-20 00:20 UTC, SzAndras1 commented on src/evoKnowledgeShare/evoKnowledgeShare.UnitTests/Repositories/UserRepositoryTests.cs
> +                user.UserName = "Admin";
user.UserName = "Admin" + i; akart lenni

2022-12-09 14:19 UTC, kealyz commented on src/evoKnowledgeShare/evoKnowledgeShare.Backend/Controllers/UserController.cs
> +        public IActionResult DeleteUserById(Guid id)
Hiányzik a delete by id

2022-12-09 14:19 UTC, kealyz commented on src/evoKnowledgeShare/evoKnowledgeShare.Backend/Repositories/UserRepository.cs
> +            return myDbContext.Users.Where(user => entities.Any(entity => entity.Id == user.Id));
NullReferenceException futás időben generálódik, nem figyelmeztetett, hogy így nem kellene használni?
```suggestion
            public override async Task<Topic> AddAsync(Topic entity)
        {
            entity.Id = Guid.NewGuid();
            try
            {
                EntityEntry<Topic> addedTopic = await myDbContext.Topics.AddAsync(entity);
                await myDbContext.SaveChangesAsync();
                return addedTopic.Entity;
            }
            catch (OperationCanceledException ex)
            {
                //TODO: Log(ex)
                throw new OperationCanceledException($"Operation exception happened during function {nameof(AddAsync)}.", ex, CancellationToken.None);
            }
        }
```

2022-12-09 14:19 UTC, kealyz commented on src/evoKnowledgeShare/evoKnowledgeShare.Backend/Repositories/UserRepository.cs
> +                throw new KeyNotFoundException();
Szerintem mégiscsak maradhatunk a DbUpdateConcurrencyException-nél. Dobjuk és kapjuk el a controllerben.

2022-12-09 14:19 UTC, kealyz commented on src/evoKnowledgeShare/evoKnowledgeShare.Backend/Repositories/UserRepository.cs
>              User? user = myDbContext.Users.FirstOrDefault(x => x.Id == id) ?? throw new KeyNotFoundException();
Szerintem áthívhatunk a másik Remove metódusba, csak a User-t query-zzük le, ha nem találunk ilyet, akkor KeyNotFoundException, amit Controllerben elkapunk.

2022-12-09 14:19 UTC, kealyz commented on src/evoKnowledgeShare/evoKnowledgeShare.Backend/Repositories/UserRepository.cs
>          public override void RemoveRange(IEnumerable<User> entities) => myDbContext.Users.RemoveRange(entities);
Itt is hasonlóan, mint a Remove-nál, try catch-ben kapjuk el a DbUpdateConcurrencyException-t.

2022-12-19 20:04 UTC, kealyz approved these changes

2022-12-19 20:09 UTC, merged