History Base Repository and Controller
kealyz/evoKnowledgeShare pull request #24
Opened 2022-12-06 09:12 UTC by marcibaumel

2022-12-06 19:03 UTC, vadaszidavid requested changes
tesztekre általánosan igazak a kommentek, nem csak ott ahová írtam, #25-ből is vedd át a kommenteket, jó példa, hogy hogy nézzen ki

2022-12-06 19:03 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.Backend/Controllers/HistoryController.cs
> +        [HttpGet("Histories")]
ez legyen `/api/History/all`, vagy `/api/History`

2022-12-06 19:03 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.Backend/Controllers/HistoryController.cs
> +        [HttpGet("History/{id}")]
legyen simán csak `/api/History/{id}`

2022-12-06 19:03 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.Backend/Controllers/HistoryController.cs
> +        [HttpPost("Create")]
legyen simán csak `/api/History/`, abból, hogy POST tudni, hogy ezzel újat hozunk létre

2022-12-06 19:03 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.Backend/Repositories/HistoryRepository.cs
> +            throw new NotImplementedException();
ne maradjon `NotImplementedException`, ha nem akarjuk támogatni, akkor inkább `NotSupportedException`

https://learn.microsoft.com/en-us/dotnet/api/system.notimplementedexception?view=net-6.0#notimplementedexception-and-other-exception-types

2022-12-06 19:03 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.IntegrationTests/Controllers/HistoryControllerTests.cs
> +
itt töltsd fel a db-t, ne a tesztekben, tedd ki egy változóba az adatokat és akkor a tesztben tudod használni, nem kell újat létrehozni, kevesebb hibalehetőség

2022-12-06 19:03 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.IntegrationTests/Controllers/HistoryControllerTests.cs
> +    public class HistoryControllerTests : ControllerTestBase
`GetHistoryById`-ra nincs teszt

2022-12-06 19:03 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.IntegrationTests/Controllers/HistoryControllerTests.cs
> +            Assert.That(history, Is.Not.Null);
nézzük meg, hogy nem azt a guid-ot kaptuk vissza amit küldtünk neki, a kliensnek nem szabad megmondania, hogy milyen id-val tegye be a db-be a backend

2022-12-06 19:03 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.UnitTests/Repositories/HistoryReposiotroyTests.cs
> +    public class HistoryReposiotroyTests
a hibás eseteket is teszteld le, legalább az exceptionöket (lehet, hogy azt beszéltük, hogy a service-ben dobunk exceptiönt és nem itt, nem emlékszem pontosan)

2022-12-06 19:03 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.IntegrationTests/Controllers/HistoryControllerTests.cs
> +        {
`Guid.NewGuid()` is megfelel

2022-12-19 19:19 UTC, kealyz approved these changes

2022-12-19 19:26 UTC, merged