Note
kealyz/evoKnowledgeShare pull request #25
Opened 2022-12-06 18:12 UTC by KercsiBence

Problems / unfinished things:

- Commenting of the methods 
- Controller tests
- Exception handle

2022-12-06 19:24 UTC, vadaszidavid requested changes

2022-12-06 19:24 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.Backend/Controllers/NoteController.cs
> +                return NotFound();
itt ilyen nem szabad, hogy jöjjön, max üres lehet a lista, de az nem hiba, inkább 204

2022-12-06 19:24 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.Backend/Controllers/NoteController.cs
> +                return NotFound();
ugyanaz, mint a `GetNotes()`

2022-12-06 19:24 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.Backend/Controllers/NoteController.cs
> +                return NotFound();
ugyanaz, mint a `GetNotes()`

2022-12-06 19:24 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.Backend/Controllers/NoteController.cs
> +                return NotFound();
ugyanaz, mint a `GetNotes()`

2022-12-06 19:24 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.Backend/Controllers/NoteController.cs
> +                return NotFound();
ugyanaz, mint a `GetNotes()`

2022-12-06 19:24 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.Backend/Interfaces/IRepository.cs
> +        /// <param name="entity"></param>
a `<summary> </summary>` is legyen megírva

2022-12-06 19:24 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.Backend/Interfaces/IRepository.cs
> +        ///<exception cref="KeyNotFoundException"></exception>
`KeyNotFoundException` ebből ne jöjjön ha üres, legyen `Enumerable.Empty<TEntity>`

2022-12-06 19:24 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.Backend/Repositories/NoteRepository.cs
> +                throw new KeyNotFoundException();
exception helyett `Enumerable.Empty<Note>`

2022-12-06 19:24 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.IntegrationTests/Controllers/NoteControllerTest.cs
> +            myContext.Notes.AddRange(myNotes);
ez úgy látom mindenhol közös, mehet a `Setup()`-ba

2022-12-06 19:24 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.IntegrationTests/Controllers/NoteControllerTest.cs
> +    internal class NoteControllerTest : ControllerTestBase
hibákra is legyen teszt

2022-12-06 19:24 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.IntegrationTests/Controllers/NoteControllerTest.cs
> +        public async Task NoteController_GetById_ShouldReturnWithOke()
nem kell az 'e' a végére

2022-12-06 19:24 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.UnitTests/Repositories/NoteRepositoryTests.cs
> +            myDbContext.SaveChanges();
feltöltés a `SetUp()`-ba

2022-12-06 19:24 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.UnitTests/Repositories/NoteRepositoryTests.cs
> +            Note expectedNote2 = myNotes[1];
nem kell rá külön változó, a lista vagy tömb is `IEnumerable<Note>`

2022-12-09 14:19 UTC, kealyz commented on src/evoKnowledgeShare/evoKnowledgeShare.Backend/Services/NoteService.cs
> +        public IEnumerable<Note> GetByUserId(Guid id) => myRepository.GetAll().Where(x => x.UserId == id).ToList();
A félreértés elkerülése végett én GetRangeByUserId-t írnék.

2022-12-09 21:32 UTC, KercsiBence commented
Ay utolso tudom hogy elo se fordulhatna productba, de igy campus soran lehet elnezheto lenne, mert azert igy egyszerubb, ennek a gitnek a wikihez nem ferunk hozza szerkesztesre egyebkent meg mindenkinek mindig frissentartani pain in the ass, igy meg az is jonne velunk ha lehuzzuk az ujat, meg abba is latnank folyamatosan hogy hogy alakulnak a dolgok, de ha rossz otlet akkor tlalajunk ki valamit hol lesznek egysegesen az exceptionok, a visszateresi statuszok, az api hivasok stb

2022-12-19 21:48 UTC, kealyz approved these changes

2022-12-19 22:31 UTC, closed without merging

2022-12-19 22:32 UTC, kealyz commented
Másik branchen ment be a változtatás.