NoteService get methods and their tests
kealyz/evoKnowledgeShare pull request #6
Opened 2022-10-23 11:21 UTC by KercsiBence

2022-10-23 11:35 UTC, kealyz reviewed
A Repositoryban lévő függvényeket nem kell módosítani/hozzáadni újakat.

2022-10-23 15:51 UTC, vadaszidavid commented
- metódusok nagy betűvel legyenek
- teszteknél a setupban csak a 2 new legyen, a többi a tesztben magában
- azt is nézze meg a teszt, hogy tényleg jó noteokat ad vissza, ne csak azt, hogy mennyit
- Note-on Equals és GetHashCode

2022-10-23 15:52 UTC, vadaszidavid requested changes
- metódusok nagy betűvel legyenek
- teszteknél a setupban csak a 2 new legyen, a többi a tesztben magában
- azt is nézze meg a teszt, hogy tényleg jó noteokat ad vissza, ne csak azt, hogy mennyit
- Note-on Equals és GetHashCode

2022-10-23 17:38 UTC, KercsiBence commented
Direkt hagytam a teszteket 2 note-al, hogy valoban jot ad e vissza

2022-10-27 06:49 UTC, vadaszidavid approved these changes, later dismissed

2022-10-27 06:52 UTC, vadaszidavid commented on src/evoKnowledgeShare/evoKnowledgeShare.Backend/Models/Note.cs
> +            if (obj?.GetHashCode())
ide még egy == true-t tegyél már be
(lehet nem kéne 9 előtt kódot reviewzni)

2022-11-03 14:36 UTC, closed without merging