Topic és TopicServices kidolgozása
kealyz/evoKnowledgeShare pull request #7
Opened 2022-10-23 17:15 UTC by oroszpeter97

Megcsináltam a Topic és TopicServices classt és megcsináltam a metódusokat.

2022-10-24 15:42 UTC, vadaszidavid requested changes
Jó lesz, teszteket még írj hozzá és mehet be. Ha kell példa, #6-ban találsz rá.

2022-10-25 15:53 UTC, vadaszidavid requested changes
Az utolsó állapotot vedd alapul, abban át vannak egy kicsit dolgozva a tesztek: 73a0ea2030b7e7f027412cc2e3f4903f18d35be4

2022-10-25 16:50 UTC, vadaszidavid commented
Előzőből kimaradt, hogy ne csinálj több setupot ugyanarra, nem biztos, hogy úgy működik ahogy gondolod

2022-11-01 08:52 UTC, oroszpeter97 commented
Kijavítottam a Topic-ot és megírtam TopicServiceTesteket.

2022-11-03 21:50 UTC, vadaszidavid commented
Merged with #13

2022-11-03 21:50 UTC, closed without merging